### PR TITLE
Reformat code with PSR + added phpdoc block

### PR DESCRIPTION
**Pull request by afu-dev**
Hello,

Following the comment on Reddit, I reformat the code to looks like less "2000x-ish". Also added PHPDOC (another suggestion from Reddit).

### CODE REVIEW

**Comment by D-Marc1** [comment]
Hey, much appreciated, man. Looks pretty good. Should have taken a look at this before I made another change. I'll review this tonight or tomorrow to resolve the conflict and merge your changes.

**Comment by afu-dev** [comment]
Hey,

Conflits resolved ;)

**Comment by D-Marc1** [comment]
Thanks, do you think we could just do PHPDoc for now? I'm indifferent about the extra lines, so I'm fine with that as well. But I think I'm still leaning towards using tabs. As for the inline, implicit `if`s, I'd like to keep that too, as I subjectively view them as more readable if they're not too long. 

I know it's not PSR-compliant, but I'm consistent with it, as you pointed out, so I think it should be ok. Sorry, I understand if you don't want to do another commit. I'd be happy to do it myself. I appreciate everything, regardless.

**Comment by D-Marc1** [comment]
Ended up thoroughly documenting this myself, following your PR. I also added some more comments and spaced it out a little better. I feel really bad I didn't merge yours, as you should get credit for this. There were just a few things I didn't want to change. Thanks again for your help! :)

**Pull request closed without merging**
